import tkinter as tk
ventana = tk.Tk()
ventana.title("cajas de texto")
ventana.minsize(500,500)
ventana.maxsize(500,500)
etiqueta1 = tk.Label(ventana,text='Digite un valor')
etiqueta1.grid(row=1, column=1, padx=5, pady=5)
caja1 = tk.Entry(ventana)
caja1.grid(row=1, column=2, padx=5, pady=5)
etiqueta2 = tk.Label(ventana,text='Digite otro valor')
etiqueta2.grid(row=3, column=1, padx=5, pady=5)
caja2 = tk.Entry(ventana)
caja2.grid(row=3, column=2, padx=5, pady=5)
ventana.mainloop()